### ISSUE TITLE
Не работает на HumHub 1.13.2.

### ISSUE THREAD

**Issue by arisudi** [WebCrew/humhub_flathub_updated#1]
Не работает на HumHub 1.13.2.
Ошибка: Undefined variable $submitUrl.

**Comment by WebCrew** [comment]
Thank you for reporting the issue to us. I'm sorry but **I can't fix this** because **I'm not good with YII Framework**. I already wrote about it in the **README file**.

If you can fix it, feel free to do it - You`re welcome.

Greetings Andreas

**Comment by WebCrew** [comment]
Thank You [felixhahnweilheim](https://github.com/felixhahnweilheim) You are awesome.

**Comment by WebCrew** [comment]
Needs still to be solved - if there is someone with Yii knowledge it would be great if you help us to fix the upload issue.

Kind regards and thats, Andreas

**Comment by felixhahnweilheim** [comment]
#3 fixes the comment form problem. I don't know any other bugs, so I close this issue.  

@WebCrew I have also fixed a typo in FUNDING.yml. And I have added my own sponsor link there, I hope that is OK with you.

**Comment by WebCrew** [comment]
Hi Felix,
of course that's ok with your sponsor link. Thanks for the correction too.

Regards, Andy
