### ISSUE TITLE
Dark mode: text contrast

### ISSUE THREAD

**Issue by felixhahnweilheim** [WebCrew/humhub_flathub_updated#6]
In dark mode some texts are not well readable, see screenshot:

![Screenshot 2023-05-06 at 22-47-23 Dashboard - Felix Hahn Development](https://user-images.githubusercontent.com/84990763/236646072-85515f6c-45b9-459d-80ac-6e0054efd555.png)

**Comment by WebCrew** [comment]
What do you think - should it be just a **little bit brighter grey** or should we give it **some kind of a very bright blue tone**?

I´ll correct the CSS issues with the text contast and also the position issue of the module icons but at the moment I have no HH setup on my rig or online. I`ll fix it in the near future.

Kind regards and thanks for the issue articles @felixhahnweilheim - You`re awesome! :)

**Comment by felixhahnweilheim** [comment]
I think a brighter grey would be enough.

**Comment by WebCrew** [comment]
Ya I think so too Felix :)

**Comment by WebCrew** [comment]
The problem **got fixed** - font is now much brighter.

People I have to tell you that repository **will become an archive now**.
We will **no longer support the theme** - it is to much work and **no fun at all anymore**.

We wish you **the best** and say thanks for your support. ;)
