### ISSUE TITLE
View of modules in space

### ISSUE THREAD

**Issue by felixhahnweilheim** [WebCrew/humhub_flathub_updated#7]
The view of modules in a space (for space administrators) is broken, see screenshot

![Screenshot 2023-05-06 at 23-02-02 Dashboard - Felix Hahn Development](https://user-images.githubusercontent.com/84990763/236646512-bdcfa4cc-74b9-49f5-8e92-826a48a02460.png)

**Comment by WebCrew** [comment]
@felixhahnweilheim Du ich hab heute extra nochmal HH aufgesetzt und wollte die beiden Fehler korrigieren, also Module Ansicht und den Grauton der Schrift. Nun ist es aber so, dass ich eine nicht geringe Menge an anderen Fehlern entdeckt habe und auch **viele Bereiche** die im Dark-Mode **gar nicht gestyled wurden** also hell bleiben. Da ist alles in allem also **viel viel mehr** zu tun und ich hab ehrlich gesagt weder sooooo viel Zeit und ehrlich gesagt auch Laune da quasi nochmal jetzt jede CSS Klasse auf Fehlerfreiheit zu prüfen und dann zu korrigieren. 

Ich klinke mich an dem Punkt aus, zumal ich HH eh nicht mehr nutze und nutzen möchte.
 
Vielleicht wäre es besser und auch einfacher, einfach die neue **Clean-Theme** (im Marktplatz als Modul) dazu zu verwenden, ihr einen Darkmode via darkmode.js zu verpassen? Das macht sicher mehr Sinn, als bei Flathub quasi nochmal neu anzufangen. Oder noch besser - man lässt als 3rd Party Hobby Entwickler besser gleich die Finger davon Themes und Module zu entwickeln, da mit deren Update Speed-Rhythmus eh kaum jemand mithalten kann. Da spart man sich also jede Menge Frust.

Nichts für Ungut Felix, sorry dafür, aber ich denke meine Ansichten sind nachvollziehbar oder?

Beste Grüße, Dir vielen Erfolg und weiterhin viel Freude am Entwickeln.

Andreas ;)

**Comment by felixhahnweilheim** [comment]
Total verständlich, ich werde es auch nicht mehr weiter entwickeln.

Was den dunklen Modus angeht, habe ich vor ein paar Tagen ein Modul veröffentlicht: https://marketplace.humhub.com/module/dark-mode/description

In Zukunft soll es auch mit dem Clean Theme funktionieren.

Wenn Themes nicht ganz so alt sind (und nur wenige views überschreiben) ist auch nicht immer so viel upzudaten.

**Comment by WebCrew** [comment]
Wow @felixhahnweilheim das Darkmode Modul ist genial - gratuliere Dir dazu. Sogar "free" obwohl ich mir sicher bin, dass viele eine dunkle Theme haben möchten, da hättest also durchaus paar Kröten damit verdienen können. Das wird vielen echte Freude bereiten. Ich hab vor Jahren mal ein Tutorial geschrieben wie man mit darkmode.js arbeitet, aber ein Modul zu machen ist natürlich gigantisch gut. Ich beneide Dich um Dein PHP / Yii Wissen :)

Die Clean-Theme ist echt gelungen und bietet sich für Darkmode eigentlich regelrecht an, da sie nicht so viel mit Farben spielt und sehr helle Farb-Töne benutzt. Das dürfte mit Darkmode ein echt tolles Ergebnis erreichen, speziell wenn man mit der Kontrast Variante von der Clean-Theme arbeitet.

Naja, wir laufen uns sicher mal wieder bei irgendeinem anderen Projekt über den Weg. Flathub ist erst mal Geschichte - schade, aber naja ist eben so ;)

Gruß, Andi ;)

**Comment by WebCrew** [comment]
The repository **will be archived** - thanks for your interest people and **we wish you a good time**. ;)
